// ============================================================================
// HOSPITAL SYSTEM ABBREVIATIONS - CLEANED VERSION
// ============================================================================
// Original: 452 abbreviations
// Removed: 24 HIGH RISK generic abbreviations
// Added: 4 compound word variations (2026-04-01)
// Added: 29 verified abbreviations (2026-04-02)
// Final: 461 abbreviations
//
// REMOVED ABBREVIATIONS (too generic, caused wrong matches):
//   "baptist" → Baptist Health
//   "baptist health" → Baptist Health
//   "baptist healthcare" → Baptist Healthcare
//   "baptist hospital" → Baptist Health
//   "baptist medical" → Baptist Health
//   "baptist memorial" → Baptist Memorial Health Care
//   "lutheran general" → Advocate Aurora Health
//   "memorial health" → Memorial Healthcare System
//   "memorial healthcare" → Memorial Healthcare System
//   "memorial hospital" → Memorial Healthcare System
//   "memorial system" → Memorial Healthcare System
//   "mercy" → Mercy Health
//   "mercy health" → Mercy Health
//   "mercy healthcare" → Mercy Health
//   "mercy hospital" → Mercy Health
//   "mercy medical" → Mercy Health
//   "methodist" → Methodist Health System
//   "methodist health" → Methodist Health System
//   "methodist hospital" → Methodist Health System
//   "presbyterian hospital" → UPMC
//   "trinity" → Trinity Health
//   "trinity health" → Trinity Health
//   "trinity healthcare" → Trinity Health
//   "trinity hospital" → Trinity Health
//
// Last updated: 2026-04-02
// ============================================================================

const ABBREVIATIONS = {
  "abbott northwestern": "Allina",
  "advent": "AdventHealth",
  "advent health": "AdventHealth",
  "adventhealth": "AdventHealth",
  "adventhealth florida": "AdventHealth",
  "adventhealth orlando": "AdventHealth",
  "adventist": "AdventHealth",
  "adventist health": "AdventHealth",
  "adventist hospital": "AdventHealth",
  "adventure health": "AdventHealth",
  "advocate": "Advocate Aurora Health",
  "advocate aurora": "Advocate Aurora Health",
  "advocate health": "Advocate Aurora Health",
  "albany medical center": "Albany Med Health System",
  "allina": "Allina",
  "allina health": "Allina",
  "allina hospital": "Allina",
  "ascension": "Ascension Illinois",
  "ascension health": "Ascension Illinois",
  "ascension providence": "Ascension - Providence HealthCare Network",
  "ascension via christi": "Ascension via Christi Hospitals, Wichita KS, Inc",
  "ascension wisconsin": "Ascension Wisconsin",
  "ascention": "Ascension Illinois",
  "assension": "Ascension Illinois",
  "atlanta childrens": "Children's Healthcare of Atlanta",
  "atrium": "Atrium Health",
  "atrium health": "Atrium Health",
  "atrium healthcare": "Atrium Health",
  "atrium hospital": "Atrium Health",
  "atrium medical": "Atrium Health",
  "aurora": "Advocate Aurora Health",
  "aurora health": "Advocate Aurora Health",
  "banner": "Banner Health",
  "banner health": "Banner Health",
  "bannerhealth": "Banner Health",
  "banner healthcare": "Banner Health",
  "banner hospital": "Banner Health",
  "banner medical": "Banner Health",
  "banner university": "Banner Health",
  "baptist jacksonville": "Baptist Health - Northeast Florida",
  "baptist memphis": "Baptist Memorial Health Care",
  "baptist miami": "Baptist Health South Florida",
  "baptist northeast florida": "Baptist Health - Northeast Florida",
  "baptist south florida": "Baptist Health South Florida",
  "barnes jewish": "BJC Healthcare & Washington University",
  "barnes-jewish": "BJC Healthcare & Washington University",
  "bassett": "Bassett Healthcare",
  "bassett health": "Bassett Healthcare",
  "bassett healthcare": "Bassett Healthcare",
  "bassett hospital": "Bassett Healthcare",
  "baylor": "Baylor",
  "baylor dallas": "Baylor",
  "baylor health": "Baylor",
  "baylor scott and white": "Baylor Scott & White Health",
  "baylor scott white": "Baylor Scott & White Health",
  "bch": "Boston Children's Hospital",
  "beaumont": "Beaumont Health",
  "beaumont health": "Beaumont Health",
  "beaumont hospital": "Beaumont Health",
  "beaumont medical": "Beaumont Health",
  "beaumont royal oak": "Beaumont Health",
  "bjc": "BJC Healthcare & Washington University",
  "bjc health": "BJC Healthcare & Washington University",
  "bjc healthcare": "BJC Healthcare & Washington University",
  "bon secours": "Mercy Health",
  "bon secours mercy": "Mercy Health",
  "brigham": "Mass General Brigham",
  "brigham and women's": "Mass General Brigham",
  "brigham and womens": "Mass General Brigham",
  "brigham womens": "Mass General Brigham",
  "brookwood baptist": "Brookwood Baptist Health",
  "bsw": "Baylor Scott & White Health",
  "bswh": "Baylor Scott & White Health",
  "bwh": "Mass General Brigham",
  "california pacific": "Sutter Health",
  "carolinas healthcare": "Atrium Health",
  "ccf": "Cleveland Clinic",
  "cchmc": "Cincinnati Children's",
  "cedars": "Cedars-Sinai",
  "cedars los angeles": "Cedars-Sinai",
  "cedars sinai": "Cedars-Sinai",
  "cedars sinai hospital": "Cedars-Sinai",
  "cedars sinai medical center": "Cedars-Sinai",
  "cedars-sinai": "Cedars-Sinai",
  "children's atlanta": "Children's Healthcare of Atlanta",
  "childrens atlanta": "Children's Healthcare of Atlanta",
  "childrens healthcare atlanta": "Children's Healthcare of Atlanta",
  "childrens hospital philadelphia": "CHOP - Children's Hospital of Philadelphia",
  "childrens memorial chicago": "Ann & Robert H. Lurie Children's Hospital of Chicago",
  "choa": "Children's Healthcare of Atlanta",
  "chop": "CHOP - Children's Hospital of Philadelphia",
  "christ hospital": "Advocate Aurora Health",
  "christ us": "CHRISTUS Health",
  "christus": "CHRISTUS Health",
  "christus health": "CHRISTUS Health",
  "christus healthcare": "CHRISTUS Health",
  "christus hospital": "CHRISTUS Health",
  "cleveland": "Cleveland Clinic",
  "cleveland clinic": "Cleveland Clinic",
  "clevelandclinic": "Cleveland Clinic",
  "cleveland clinic florida": "Cleveland Clinic",
  "cleveland clinic las vegas": "Cleveland Clinic",
  "cleveland clinic ohio": "Cleveland Clinic",
  "cleveland clinical": "Cleveland Clinic",
  "clevland clinic": "Cleveland Clinic",
  "columbia": "Columbia University Irving Medical Center",
  "columbia irving": "Columbia University Irving Medical Center",
  "columbia medical center": "Columbia University Irving Medical Center",
  "columbia presbyterian": "Columbia University Irving Medical Center",
  "columbia university": "Columbia University Irving Medical Center",
  "comer children's hospital": "University of Chicago Hospitals",
  "comer childrens": "University of Chicago Hospitals",
  "cornell": "Weill Cornell Medicine ",
  "cornell medical": "Weill Cornell Medicine ",
  "cornell medicine": "Weill Cornell Medicine ",
  "cpmc": "Sutter Health",
  "cuimc": "Columbia University Irving Medical Center",
  "duke": "Duke University Health System",
  "duke health": "Duke University Health System",
  "duke hospital": "Duke University Health System",
  "duke medical center": "Duke University Health System",
  "duke medicine": "Duke University Health System",
  "duke university hospital": "Duke University Health System",
  "emory": "Emory Healthcare",
  "emory atlanta": "Emory Healthcare",
  "emory health": "Emory Healthcare",
  "emory healthcare": "Emory Healthcare",
  "emory hospital": "Emory Healthcare",
  "emory university hospital": "Emory Healthcare",
  "essentia": "Essentia Health",
  "essentia duluth": "Essentia Health",
  "essentia health": "Essentia Health",
  "essentia healthcare": "Essentia Health",
  "essentia hospital": "Essentia Health",
  "florida hospital": "AdventHealth",
  "forsyth medical": "Novant Health Partners",
  "geisinger": "Geisinger",
  "geisinger clinic": "Geisinger",
  "geisinger health": "Geisinger",
  "geisinger hospital": "Geisinger",
  "geisinger medical": "Geisinger",
  "hartford": "Hartford HealthCare",
  "hartford health": "Hartford HealthCare",
  "hartford healthcare": "Hartford HealthCare",
  "hartford hospital": "Hartford HealthCare",
  "hca": "HCA",
  "hca health": "HCA",
  "hca healthcare": "HCA",
  "hca hospital": "HCA",
  "hca medical": "HCA",
  "hhc": "Hartford HealthCare",
  "hopkins": "Johns Hopkins Medicine",
  "hopkins baltimore": "Johns Hopkins Medicine",
  "hopkins medicine": "Johns Hopkins Medicine",
  "hospital corporation of america": "HCA",
  "hospital of the university of pennsylvania": "Penn Medicine",
  "houston methodist": "Houston Methodist",
  "hup": "Penn Medicine",
  "hyde park hospital": "University of Chicago Hospitals",
  "ingalls hospital": "University of Chicago Hospitals",
  "ingalls memorial": "University of Chicago Hospitals",
  "intermountain": "Intermountain Health",
  "intermountain health": "Intermountain Health",
  "intermountain healthcare": "Intermountain Health",
  "intermountain hospital": "Intermountain Health",
  "intermountain medical": "Intermountain Health",
  "jefferson": "Thomas Jefferson University Health System",
  "jefferson health": "Thomas Jefferson University Health System",
  "jefferson hospital": "Thomas Jefferson University Health System",
  "jhh": "Johns Hopkins Medicine",
  "jhu": "Johns Hopkins Medicine",
  "john hopkins": "Johns Hopkins Medicine",
  "johns hopkin": "Johns Hopkins Medicine",
  "johns hopkins": "Johns Hopkins Medicine",
  "johns hopkins hospital": "Johns Hopkins Medicine",
  "kaiser": "Kaiser Permanente - Northern California",
  "kaiser california": "Kaiser Permanente - Northern California",
  "kaiser colorado": "Kaiser Permanente - Colorado",
  "kaiser hawaii": "Kaiser Permanente - Hawaii",
  "kaiser norcal": "Kaiser Permanente - Northern California",
  "kaiser northern california": "Kaiser Permanente - Northern California",
  "kaiser permanente": "Kaiser Permanente - Northern California",
  "kaiser socal": "Kaiser Permanente - Southern California",
  "kaiser southern california": "Kaiser Permanente - Southern California",
  "kaiser washington": "Kaiser Permanente - Washington",
  "kayser": "Kaiser Permanente - Northern California",
  "keiser": "Kaiser Permanente - Northern California",
  "kp": "Kaiser Permanente - Northern California",
  "lds hospital": "Intermountain Health",
  "lucile packard": "Stanford Children's Health",
  "lurie": "Ann & Robert H. Lurie Children's Hospital of Chicago",
  "lurie chicago": "Ann & Robert H. Lurie Children's Hospital of Chicago",
  "lurie children's": "Ann & Robert H. Lurie Children's Hospital of Chicago",
  "lurie childrens": "Ann & Robert H. Lurie Children's Hospital of Chicago",
  "magee women's": "UPMC",
  "magee womens": "UPMC",
  "mass gen": "Mass General Brigham",
  "mass general": "Mass General Brigham",
  "massachusetts general": "Mass General Brigham",
  "may clinic": "Mayo Clinic",
  "mayo": "Mayo Clinic",
  "mayo arizona": "Mayo Clinic",
  "mayo clinic": "Mayo Clinic",
  "mayoclinic": "Mayo Clinic",
  "mayo florida": "Mayo Clinic",
  "mayo jacksonville": "Mayo Clinic",
  "mayo minnesota": "Mayo Clinic",
  "mayo rochester": "Mayo Clinic",
  "mayo scottsdale": "Mayo Clinic",
  "memorial florida": "Memorial Healthcare System",
  "memorial health hca": "Memorial Health HCA South",
  "mercy iowa": "Mercy Health",
  "mercy services": "Mercy Health Services",
  "mercy st louis": "Mercy Health Services",
  "methodist houston": "Houston Methodist",
  "methodist le bonheur": "Methodist Le Bonheur Healthcare",
  "mgb": "Mass General Brigham",
  "mgh": "Mass General Brigham",
  "michigan health": "University of Michigan Health",
  "michigan medicine": "University of Michigan Health",
  "mount sinai": "Health Center, powered by Mount Sinai",
  "mount sinai florida": "Mount Sinai Florida",
  "mount sinai hospital": "Health Center, powered by Mount Sinai",
  "mount sinai new york": "Mount Sinai New York - Concierge Care",
  "mt sinai": "Health Center, powered by Mount Sinai",
  "mt. sinai": "MountSinai",
  "naples community": "NCH Healthcare System",
  "nch": "NCH Healthcare System",
  "nch health": "NCH Healthcare System",
  "nch healthcare": "NCH Healthcare System",
  "nm": "Northwestern Medicine",
  "nmh": "Northwestern Medicine",
  "north well": "Northwell Health",
  "northwestern": "Northwestern Medicine",
  "northwestern chicago": "Northwestern Medicine",
  "northwestern hospital": "Northwestern Medicine",
  "northwestern medicine": "Northwestern Medicine",
  "northwestern memorial": "Northwestern Medicine",
  "norton": "Norton Healthcare",
  "norton health": "Norton Healthcare",
  "norton healthcare": "Norton Healthcare",
  "norton hospital": "Norton Healthcare",
  "novant": "Novant Health Partners",
  "novant health": "Novant Health Partners",
  "novant healthcare": "Novant Health Partners",
  "novanth": "Novant Health Partners",
  "nyp": "New York Presbyterian",
  "nyu": "NYU Langone",
  "nyu langone": "NYU Langone",
  "ochsner": "Ochsner Health System",
  "ochsner health": "Ochsner Health System",
  "ochsner louisiana": "Ochsner Health System",
  "oschner": "Ochsner Health System",
  "osf": "OSF HealthCare",
  "osf health": "OSF HealthCare",
  "osf healthcare": "OSF HealthCare",
  "osf hospital": "OSF HealthCare",
  "osfhealthcare": "OSF HealthCare",
  "oxner": "Ochsner Health System",
  "packard childrens": "Stanford Children's Health",
  "partners": "Mass General Brigham",
  "partners healthcare": "Mass General Brigham",
  "peidmont": "Piedmont Healthcare",
  "penn": "Penn Medicine",
  "penn health": "Penn Medicine",
  "penn medicine": "Penn Medicine",
  "pennmedicine": "Penn Medicine",
  "phs": "Providence Health & Services",
  "piedmont": "Piedmont Healthcare",
  "piedmont atlanta": "Piedmont Healthcare",
  "piedmont health": "Piedmont Healthcare",
  "piedmont hospital": "Piedmont Healthcare",
  "pitt med": "UPMC",
  "pitt medical": "UPMC",
  "primary childrens": "Intermountain Health",
  "prime": "Prime Healthcare",
  "prime health": "Prime Healthcare",
  "prime healthcare": "Prime Healthcare",
  "prime hospital": "Prime Healthcare",
  "providence": "Providence Health & Services",
  "providence alaska": "Providence Health & Services - Alaska",
  "providence ascension": "Ascension - Providence HealthCare Network",
  "providence health": "Providence Health & Services",
  "providence healthcare": "Providence Health & Services",
  "providence hospital": "Providence Health & Services",
  "providence medical": "Providence Health & Services",
  "rainbow babies": "University Hospitals Cleveland",
  "rainbow babies and childrens": "University Hospitals Cleveland",
  "robert wood johnson": "RWJBarnabas Health",
  "rush": "Rush University Medical Center",
  "rush medical center": "Rush University Medical Center",
  "rush university": "Rush University Medical Center",
  "rwj barnabas health": "RWJBarnabas Health",
  "saint barnabas": "St. Barnabas Health",
  "saint barnabas health": "St. Barnabas Health",
  "saint charles": "St. Charles Health System",
  "saint charles health": "St. Charles Health System",
  "saint david": "St. David's",
  "saint davids": "St. David's",
  "saint elizabeth": "St. Elizabeth Healthcare",
  "saint francis": "Saint Francis Health System",
  "saint francis health": "Saint Francis Health System",
  "saint joseph": "St. Joseph Hospital Health Center",
  "saint josephs": "St. Joseph Hospital Health Center",
  "saint luke": "Saint Luke's Health System",
  "saint lukes": "Saint Luke's Health System",
  "saint lukes university": "St. Luke's University Health Network",
  "saint vincent": "Ascension Illinois",
  "sandford": "Sanford Health",
  "sanford": "Sanford Health",
  "sanford bismarck": "Sanford Health",
  "sanford fargo": "Sanford Health",
  "sanford health": "Sanford Health",
  "sanford healthcare": "Sanford Health",
  "scott and white": "Baylor Scott & White Health",
  "shadyside": "UPMC",
  "sharp": "Sharp HealthCare",
  "sharp health": "Sharp HealthCare",
  "sharp healthcare": "Sharp HealthCare",
  "sharp hospital": "Sharp HealthCare",
  "sinai": "MountSinai",
  "sluh": "St. Luke's University Health Network",
  "st barnabas": "St. Barnabas Health",
  "st barnabas health": "St. Barnabas Health",
  "st charles": "St. Charles Health System",
  "st charles health": "St. Charles Health System",
  "st david": "St. David's",
  "st davids": "St. David's",
  "st e": "St. Elizabeth Healthcare",
  "st elizabeth": "St. Elizabeth Healthcare",
  "st elizabeth healthcare": "St. Elizabeth Healthcare",
  "st elizabeth hospital": "St. Elizabeth Healthcare",
  "st francis": "St. Francis Health",
  "st francis health": "St. Francis Health",
  "st francis hospital": "St. Francis Health",
  "st joes": "St. Joseph Hospital Health Center",
  "st joseph": "St. Joseph Hospital Health Center",
  "st josephs": "St. Joseph Hospital Health Center",
  "st luke": "Saint Luke's Health System",
  "st lukes": "Saint Luke's Health System",
  "st lukes penn": "St. Luke's University Health Network",
  "st lukes pennsylvania": "St. Luke's University Health Network",
  "st lukes university": "St. Luke's University Health Network",
  "st vincent": "Ascension Illinois",
  "stanford": "Stanford",
  "stanford children's": "Stanford Children's Health",
  "stanford childrens": "Stanford Children's Health",
  "stanford health": "Stanford",
  "stanford healthcare": "Stanford",
  "stanford hospital": "Stanford",
  "stanford medical center": "Stanford",
  "stanford medicine": "Stanford",
  "sutter": "Sutter Health",
  "sutter health": "Sutter Health",
  "sutter healthcare": "Sutter Health",
  "sutter medical": "Sutter Health",
  "swedish": "Providence Health & Services",
  "tch": "Texas Children's",
  "temple": "TempleHealth",
  "temple health": "TempleHealth",
  "temple university hospital": "TempleHealth",
  "tgh": "Tampa General Hospital",
  "thomas jefferson": "Thomas Jefferson University Health System",
  "trinity health new england": "Trinity Health of New England",
  "trinity new england": "Trinity Health of New England",
  "tristar": "HCA",
  "u chicago": "University of Chicago Hospitals",
  "u of c": "University of Chicago Hospitals",
  "u of c medicine": "University of Chicago Hospitals",
  "u of chicago": "University of Chicago Hospitals",
  "u of m": "University of Michigan Health",
  "u of m health": "University of Michigan Health",
  "u pmc": "UPMC",
  "uc los angeles": "UCLA Medical Center",
  "uc medicine": "University of Chicago Hospitals",
  "uc san francisco": "UCSF Health",
  "uchicago": "University of Chicago Hospitals",
  "uchicago medicine": "University of Chicago Hospitals",
  "ucla health": "UCLA Medical Center",
  "ucla hospital": "UCLA Medical Center",
  "ucla medical center": "UCLA Medical Center",
  "ucm": "University of Chicago Hospitals",
  "ucmc": "University of Chicago Hospitals",
  "ucsf health": "UCSF Health",
  "ucsf hospital": "UCSF Health",
  "ucsf medical center": "UCSF Health",
  "uh": "University Hospitals Cleveland",
  "uh cleveland": "University Hospitals Cleveland",
  "umich": "University of Michigan Health",
  "university hospitals": "University Hospitals Cleveland",
  "university hospitals cleveland": "University Hospitals Cleveland",
  "university of alabama": "UAB Medecine",
  "university of california los angeles": "UCLA Medical Center",
  "university of california san francisco": "UCSF Health",
  "university of chiacgo": "University of Chicago Hospitals",
  "university of chicago": "University of Chicago Hospitals",
  "university of chicago medical center": "University of Chicago Hospitals",
  "university of chicago medicine": "University of Chicago Hospitals",
  "university of colorado": "UCHealth",
  "university of pennsylvania": "Penn Medicine",
  "university of pittsburgh": "UPMC",
  "university of pittsburgh medical center": "UPMC",
  "upenn": "Penn Medicine",
  "upenn medicine": "Penn Medicine",
  "upm": "UPMC",
  "upmc pittsburgh": "UPMC",
  "vanderbilt": "Vanderbilt University Medical Center",
  "vanderbilt hospital": "Vanderbilt University Medical Center",
  "vanderbilt medical": "Vanderbilt University Medical Center",
  "vanderbilt nashville": "Vanderbilt University Medical Center",
  "vanderbilt university": "Vanderbilt University Medical Center",
  "via christi": "Ascension via Christi Hospitals, Wichita KS, Inc",
  "via christi wichita": "Ascension via Christi Hospitals, Wichita KS, Inc",
  "vumc": "Vanderbilt University Medical Center",
  "wake baptist": "Wake Forest Baptist Health",
  "wake forest": "Wake Forest Baptist Health",
  "wake forest baptist": "Wake Forest Baptist Health",
  "wake forest hospital": "Wake Forest Baptist Health",
  "washington university": "BJC Healthcare & Washington University",
  "weill cornell": "Weill Cornell Medicine ",
  "well star": "WellStar",
  "wellstar": "WellStar",
  "wellstar health": "WellStar",
  "wellstar hospital": "WellStar",
  "wellstar medical": "WellStar",
  "wfbh": "Wake Forest Baptist Health",
  "wustl": "BJC Healthcare & Washington University",
  "yale": "Yale New Haven Health/Yale Medical Group",
  "yale hospital": "Yale New Haven Health/Yale Medical Group",
  "yale medicine": "Yale New Haven Health/Yale Medical Group",
  "yale new haven": "Yale New Haven Health/Yale Medical Group",
  "ynhh": "Yale New Haven Health/Yale Medical Group",

  //Added 2026-04-02
"anschutz": "UCHealth",

// Arizona Oncology (full name only)
"arizona oncology of us oncology network": "US Oncology",

// Baylor
"baylor college of medicine": "Baylor",

// Blue Ridge
"blue ridge cancer care": "Blue Ridge Medical Center",

// Community Health Systems
"chs": "Community Health Systems",

// Froedtert / Medical College of Wisconsin
"medical college of wisconsin": "Froedtert",

// Hackensack Meridian
"hmh": "Hackensack Meridian Health Hackensack NJ",
"john theurer cancer center": "Hackensack Meridian Health Hackensack NJ",
"theurer": "Hackensack Meridian Health Hackensack NJ",

// Henry Ford (compound word)
"henryford": "Henry Ford Health",

// Intermountain (IHC)
"ihc": "Intermountain Health",

// Jersey Shore
"jersey shore university medical center": "Jersey Shore Hospital",

// Kansas Health System (compound word only)
"kansashealthsystem": "The University of Kansas Health System",

// Memorial Sloan Kettering (MSK initialism only)
"msk": "Memorial Sloan Kettering Cancer Center",

// MyMercy
"mymercy": "Mercy Health",

// OSF (specific facility only)
"osf little company of mary": "OSF HealthCare",

// Providence (ultra-specific only)
"providence health and services oregon and california": "Providence Health & Services",

// Riverside (portal searches only)
"epic mychart riverside healthcare": "Riverside Health System",
"mychart riverside healthcare": "Riverside Health System",
"riverside healthcare mychart epic": "Riverside Health System",

// RWJBarnabas (initialisms and facility names)
"rwjhp": "RWJBarnabas Health",
"rwjhp steeplechase": "RWJBarnabas Health",
"steeplechase": "RWJBarnabas Health",

// St. Luke's (portal search only)
"slhs my chart": "Saint Luke's Health System",

// Sutter / PAMF
"palo alto medical foundation": "Sutter Health",
"pamf": "Sutter Health",

// UPMC (specific facility)
"upmc magee breast cancer": "UPMC",

// VCU (MCV initialism only)
"mcv": "VCU Health",

// West Virginia University
"wvu": "West Virginia University Medicine"


};

module.exports = ABBREVIATIONS;
